---
# defaults file for ansible-tower
ansible_devel: false
dns_domain_name: "example.com"
# Grab the private IP of your windows DNS for your lab dns server
dns_server: "{{ hostvars['windc'].ansible_host }}"

# AD login info
authconfig_options:
  - "--enablesssd"
  - "--enablesssdauth"
  - "--enablemkhomedir"
  - "--enablelocauthorize"
  - "--update"
  - "--nostart"
ldap_search_base: "DC=example,DC=com"
ldap_access_filter: "(&(objectClass=user)(memberOf=CN=LinuxServers,CN=Users,DC=example,DC=com))"
#ldap_access_filter: "(&(objectClass=user)(|(memberOf=CN=OSunix,OU=UnixServers,DC=example,DC=com)(memberOf=CN=DBAunix,OU=UnixServers,DC=example,DC=com)))"
#ldap_access_filter: "(&(objectClass=user)(|(sAMAccountName=john)(sAMAccountName=merry)))"

towerchk: undefined

# Tower Admin Password
towerpass: "mypassword"
towerversion: 3.2.2
pgpass: awx
rabbitpass: tower
